version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run start

  mysql:
    image: mysql:8.0
    ports:
      - "3360:3306"  # Keep the MySQL port mapping as is
    environment:
      MYSQL_DATABASE: ${LOCAL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${LOCAL_DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${LOCAL_DB_PASSWORD}
      MYSQL_USER: ${LOCAL_DB_USER}
    volumes:
      - mysql-data:/var/lib/mysql  # Persist MySQL data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8006:80"  # Expose phpMyAdmin on port 8080
    environment:
      PMA_HOST: mysql  # Link phpMyAdmin to the MySQL service
      PMA_PORT: 3360  # The MySQL port
    depends_on:
      - mysql  # Wait for MySQL to be up before starting phpMyAdmin

volumes:
  mysql-data:  # Named volume for MySQL data persistence
